### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by psyfreaky** [thundernest/quicktext#12]
The setting "View Quicktext-menu on right-click" can't be checked. It is not possible to show QuickText in menu, only as toolbar ...

**Comment by spong57** [comment]
I have the same problem, who have a solution ?

**Comment by dmahler1** [comment]
i have the same problem

**Comment by specialbrewski** [comment]
Same here :(

**Comment by jobisoft** [comment]
this bug slipped into the settings migration code, no need for further confirmation. it is there. it will be fixed.

**Comment by jobisoft** [comment]
Fixed?

https://bugzilla.mozilla.org/show_bug.cgi?id=1391020#c65

Due to double review process, it will take a while, before it will show up at AMO. If this fixes your issue, please close this.

**Comment by spong57** [comment]
Sorry but no, i tried the 0.9.15 with thunderbird 52.8.0 32bits and i have the same problem. When i check the combo for the right-clic and save the settings, the combo become unchecked immediatly.
Thanks

**Comment by dmahler1** [comment]
YES,  the same thing happens to me.  Is there a fix?

**Comment by jobisoft** [comment]
You tried the wrong version. That link is pointing to v1.1

v1.1 has now officially released here as well
https://addons.mozilla.org/en-US/thunderbird/addon/quicktext/

Please try again.

**Comment by spong57** [comment]
I will test the version 0.9.14-beta and the option of combo work thin. To fix it use this [link for 0.9.14-beta](https://bugzilla.mozilla.org/attachment.cgi?id=8975746)

**Comment by jobisoft** [comment]
guys? It is fixed in v1.1 !
https://addons.mozilla.org/en-US/thunderbird/addon/quicktext/

**Comment by dmahler1** [comment]
wont install because its not verified..  I am attempting to open with 
firefox... should I try another program???

**Comment by jobisoft** [comment]
This will of course not work with firefox, it is an addon for thunderbird. I assume you have trouble downloading the new version and installing it manually in Thunderbird? 

1. You need to save the XPI to disc (right-click on the download link)
2. open thunderbird, go to the addon page
3. manually install the downloaded file via the gear icon menu

or use the addon update function (since v1.1 has been released officially) 

1. open thunderbird, go to the addon page 
2. select "check for updates" from the gear icon menu.

**Comment by dmahler1** [comment]
bam!!!~   it worked.  thanks so much john!!!

**Comment by jobisoft** [comment]
@psyfreaky Can you close this?

**Comment by jobisoft** [comment]
Can someone close this? It is fixed in v1.1.
