### ISSUE TITLE
Compatibility broken to Thunderbird 68.4.1

### ISSUE THREAD

**Issue by mtox** [thundernest/quicktext#120]
Quicktext does not work after update to Thunderbird 68.4.1

**Comment by mtox** [comment]
Problem: Thunderbird forwards the client to a incompatibility message.
But last version available here is working: https://addons.thunderbird.net/de/thunderbird/addon/quicktext/

**Comment by jobisoft** [comment]
yeah, stupid bug in TB. You would have gotten the new version tomorrow via standard update check. He just does not do it right after the update.

**Comment by sanvimart** [comment]
Sorry, are you saying TB will be updated tomorrow, which will then be compatible with Quicktext?

**Comment by jobisoft** [comment]
No. Want I wanted to say is, that Quicktext has been compatible with TB68 since summer 2019.

However, Thunderbird does not CHECK for a compatible version of Quicktext after the update from TB60 to TB68 and just tells you that the current version you have installed (the one compatible with TB60) is not compatible with TB68.

You either have to wait one day, until TB is doing the update check automatically and pulls the compatible version or you check for updates manually (via the gear menu in the add-on manager).

**Comment by sanvimart** [comment]
Ok, thank you.  That makes sense.  And it worked! Cheers.
