### ISSUE TITLE
Quicktext addon - Location of the template file

### ISSUE THREAD

**Issue by nwgilbert** [thundernest/quicktext#126]
Hi there, We use your add-on for thunderbird – Quicktext. I love it, big thank you for developing this add-on, it’s very useful.

I am wondering if it would be possible to change the location of the template file which Quicktext reads from.

Currently it is stored in a folder and I would like to move that location to another folder so that the template data is held on a cloud drive which I access across different computers.

This would mean the Quicktext templates can be updated across different devices rather than being held in a particular local file drive.

Would it be possible to relocate that template file which Quicktext finds its email template data?

Many thanks, I look forward to hearing from you.

Nick

**Comment by jobisoft** [comment]
I added an advanced option:

**Comment by jobisoft** [comment]
![grafik](https://user-images.githubusercontent.com/5830621/73572853-2cfd9c00-4472-11ea-985a-353f9b412b1f.png)

where you can define an alternative location. Would that be enough?

**Comment by jobisoft** [comment]
I just realized, this feature could cause data loss, as QuickText is only loading settings during app start. 

Imagine the current state is "A" and Computer "1" and "2" have started Quicktext and both see status "A" currently stored on the mounted cloud drive. If now computer "1" makes changes and saves them, he now is at state "A1", Computer "2" does not see that, he is still at state "A". He would only see "A1" after a restart.

If Computer "2" is doing also changes to the original state "A" and saves them as state "A2" to the mounted cloud drive, he overwrites the changes from Computer "1" and the next time Computer "1" restarts, he sees state "A2" instead of "A1".

You need to be aware of that.

What might help here is a master - salve setup: You only change the storage location on one computer (the master) and that reads and writes to your mounted cloud drive. All other computers use the "ImportOnStartup" feature:

![grafik](https://user-images.githubusercontent.com/5830621/73589179-218e8d00-44d3-11ea-86e4-6005880ebac0.png)

If you specify the template file (and also the script file if you need) from your mounted cloud drive in that field, they will load them as **readonly**.

Can you give me feedback, if the new advanced option `extensions.quicktext.settingsFolder` would solve your issue? I will not do changes to the general store/save logic of quicktext.

**Comment by nwgilbert** [comment]
@jobisoft  Thank you so much for the feedback and solution above.

This would work for us but could you please clarify if we need an alternative or updated version of Quicktext to implement this?

**Comment by jobisoft** [comment]
Check out this version :
[quicktext_pre.xpi](https://github.com/thundernest/quicktext/files/4220103/quicktext.zip)

You must uninstall you current version, restart TB, close AddOnManger, reopen AddOnManger and than install this file via the gear menu in the AddOnManager.

**Comment by nwgilbert** [comment]
Hi @jobisoft Just wanted to say thank you so much for the support and additional feature above.
I've finally got around to adding it to our Thunderbird mail for use to share across our online cloud drive for multiple devices to access the same quicktext file.

Can you please clarify what we should put into this field? Would this be the file location?
If so, what format should this be in?
![image](https://user-images.githubusercontent.com/57526570/80642391-507ab780-8a5e-11ea-900a-e1d341dc43d5.png)

Further to this, I am concerned this solution will only allow us to edit the template file on one device.
I would like to clarify that we would only have one user updating the template at any given time, this means we would not have two users updating the file across two different devices without thunderbird being restarted - this is not a concern as the cloud drive continually syncs files to the latest version so as soon as one user updates, and another user loads the device and thunderbird, it should have the latest version of Quicktext.

Would it be possible to have it so that we have a custom file location which is held on the cloud drive? Every device with Thunderbird and Quicktext is setup so that it reads from the same file which is held on a cloud drive.

User 1 updates the template on Device A and when clicking save in Quicktext, this will update the file held on the cloud drive.
This means when User 1 loads Thunderbird with Quicktext on Device B, it will have the latest version as it is on Device A.

Sorry if the above already does that, just wasn't quite sure if this was restricted so that we can only update the file on one device?

**Comment by nwgilbert** [comment]
Hi John @jobisoft
Just wondering if you can advise on the above please?

**Comment by jobisoft** [comment]
Give me a few days.

**Comment by nwgilbert** [comment]
Hi John @jobisoft just wanted to see if you have a further update on my comments above.
Thanks, look forward to hearing from you soon.

**Comment by jobisoft** [comment]
We moved and my office in the new home is not yet setup. It will take a few more days.

**Comment by nwgilbert** [comment]
@jobisoft No problem thank you!

**Comment by nwgilbert** [comment]
Hi John @jobisoft hope you are well, just wanted to see if you are back up and running and when you have a chance to look into the above? Thanks!

**Comment by nwgilbert** [comment]
Hi @jobisoft can you please look into this above when you have some time?

**Comment by jobisoft** [comment]
A lot has changed since 2020. Quicktext has moved away from the preference system and stores his preferences in the local storage, which is currently not accessible from the outside. I added a special preference for this now:

`extensions.quicktext.templateFolderOverride`

You can use that preference to tell Quicktext to not use the local profile folder to store templates, but instead use the path set in the special `templateFolderOverride` preference shown above.

For example, if your shared templates are stored on a windows share on `\\Server\quicktext\templates.xml` then mount that share to a local drive so the file is accessible via a drive letter like `Q:\templates.xml`. If that works, set the `templateFolderOverride` preference introduced above to `Q:\`.

But I do not suggest using that feature with multiple systems accessing the same templates file, that will most probably lead to data loss. Instead - as suggested before - I propose to include the default templates on each system. If the share as been mounted as shown above, enter `Q:\templates.xml` in the field pointed out by yourself here:

![grafik](https://user-images.githubusercontent.com/5830621/120658186-81a99080-c485-11eb-8c47-880b9bb67aec.png)

This will load all the templates stored on the central server, read-only.

This does not work with the released version 3.6 available on ATN, only with the unreleased developer verison 3.7b1 available here on github. Release will be in a couple of days.

**Comment by nwgilbert** [comment]
Hi John @jobisoft ,
Thanks for following up on this request as we never actually got to a working solution. We would like to get this sorted now.

The drive we would like to host the Quicktext template file is on Google Drive (online cloud drive).
The problem with the solution above (for example using Q:\ or particular drives on the system) is that the Google Drive may be stored in a slightly different local storage location on each computer.
For example, 
On computer 1: it may be held on E:\google-drive\quicktext-template-file\templates.xml
On computer 2: it may be held on F:\google-drive\quicktext-template-file\templates.xml

Since the drives are different (meaning a different file location), I guess this can be set on each computer depending on the slightly different file location via the field entered on each computer?

I know you have said that you do not suggest sharing across multiple devices due to potential data loss, but only one person would use the template file at any time. This means only one person would be updating the file at any given time so I don't see this being an issue.

It would be useful to know if Quicktext only loads the template file at the time of opening thunderbird? So each time Thunderbird is restarted, it would load the latest template file accessible? - is that correct?

Thanks for your support on this request. Look forward to hearing back.

**Comment by jobisoft** [comment]
> Since the drives are different (meaning a different file location), I guess this can be set on each computer depending on the slightly different file location via the field entered on each computer?

Yes.
 
> I know you have said that you do not suggest sharing across multiple devices due to potential data loss, but only one person would use the template file at any time. This means only one person would be updating the file at any given time so I don't see this being an issue.
> 
> It would be useful to know if Quicktext only loads the template file at the time of opening thunderbird? So each time Thunderbird is restarted, it would load the latest template file accessible? - is that correct?

Yes.

**Comment by nwgilbert** [comment]
Hi John @jobisoft ,
I'm a little confused as to how we should carry this out due to this solution being spread over such a long time.
Would you mind recapping on the instructions as I know back in 2020 you said to use this below:
> Check out this version :
> [quicktext_pre.xpi](https://github.com/thundernest/quicktext/files/4220103/quicktext.zip)
> 
> You must uninstall you current version, restart TB, close AddOnManger, reopen AddOnManger and than install this file via the gear menu in the AddOnManager.

but then you said alot has changed and gave some other instructions.

Would you mind clarifying again the best way to set this up so I can do this across numerous devices to be accessing the same template file? Can i use the latest version of quicktext for this or should i use your version tagged above?

**Comment by nwgilbert** [comment]
Hi @jobisoft , are you able to confirm the above please?

I am not sure the best way to do this since you said that the later versions of QuickText has additional functions?

Should I still be using the older version linked above for this solution to share the same template file across numerous devices?

**Comment by nwgilbert** [comment]
Hi @jobisoft can you please let us know about the above? Should we still be using the old version for this solution?

**Comment by jobisoft** [comment]
Ok. It should work as follows (with the most recent version of QuickText)

> For example,
On computer 1: it may be held on E:\google-drive\quicktext-template-file\templates.xml
On computer 2: it may be held on F:\google-drive\quicktext-template-file\templates.xml
Since the drives are different (meaning a different file location), I guess this can be set on each computer depending on the slightly different file location via the field entered on each computer?

On each computer, you have to define the appropriate location in

`extensions.quicktext.templateFolderOverride`

Close Quicktext before changing the value. With the above examples :

Computer 1: Set it to `E:\google-drive\quicktext-template-file\`
Computer 2: Set it to `F:\google-drive\quicktext-template-file\`

And it should work.

**Comment by soporteib** [comment]
Hello, What is the file where the Quicktext configuration is saved in Thunderbird 115? In quite previous versions they were saved in Globan-settings.js, but now I can't locate it.
