### ISSUE TITLE
feat(tag): add yearname tag

### ISSUE THREAD

**Issue by Elo44** [thundernest/quicktext#134]
Hi, 

Is it possible to add a new tag for year (like monthtag but for year)?

Also, how can I set a script that displays automatically a month +1 or/and a year +1
Example : 
We are in January, I want to dispay February. We are in 2020, I want to display 2021
Is it possible?

Thanks a lot for your answer

Elodie

**Comment by jobisoft** [comment]
A simple script to get the year would be:

```
// get current timeStamp
let timeStamp = Date.now();

// define options
let options = {year: "numeric"};

// get the formatted timeStamp
let formatted = new this.mWindow.Services.intl.DateTimeFormat(null, options).format(timeStamp);

return (formatted + 1);
```

Since the formatted value is a year and thus a number, I can simply add 1 to get the next year.
To get the current month as a numeric, use the following options:

```
let options = {month: "numeric"};
```

And you can again add 1, but you would need to do some edge case handling for december. If you want to have the actual name of the next month, a more complex script is needed.

I may add the year option to QT later.

**Comment by SamuelPlentz** [comment]
I just created a Community Script [DateOffset](https://github.com/thundernest/quicktext/wiki/Script:-DateOffset) that can add days, months or years. It also can display the year "standalone".

Hope it helps.

**Comment by jobisoft** [comment]
With the new community script, this issue is well solved. Thanks @SamuelPlentz !

**Comment by Elo44** [comment]
Thanks  A LOT @SamuelPlentz and @jobisoft for solving this issue so quickly! Really great!
