### ISSUE TITLE
Add buttons to access options

### ISSUE THREAD

**Issue by SamuelPlentz** [thundernest/quicktext#189]
I am trying to get buttons for quick access to the Quicktext options to work.

**Main window:**
![main](https://user-images.githubusercontent.com/1890854/96199709-6d496f80-0f58-11eb-80ed-f53aad5b21b8.png)

**Compose window:**
![mail](https://user-images.githubusercontent.com/1890854/96199710-6de20600-0f58-11eb-82db-f58a8c1e084f.png)

I successfully can write a log message to the console. However I fail to open the Quicktext options. Tried it in several places.
Here is my current code: [quicktext_button.zip](https://github.com/jobisoft/quicktext/files/5388530/quicktext_button.zip)

Here is my try in `background.js`, there is another one in `quicktext.js`.
``` Javascript
  browser.composeAction.onClicked.addListener(function() { 
    console.log("composeAction");
    
    // quicktext.openSettings();
    
    // var settingsHandle = window.open("chrome://quicktext/content/settings.xhtml", "quicktextConfig", "chrome,resizable,centerscreen");
    // settingsHandle.focus();
  });
  browser.browserAction.onClicked.addListener(function() { 
    console.log("browserAction");
    
    // quicktext.openSettings();
    
    // var settingsHandle = window.open("chrome://quicktext/content/settings.xhtml", "quicktextConfig", "chrome,resizable,centerscreen");
    // settingsHandle.focus();
  });
```

@jobisoft: Can you give me a hint, how or where to call it?

**Comment by jobisoft** [comment]
Did not look at the code in the zip, you mean you added browser and compose actions to manifest.json in order to use those buttons to open the options tab? That is currently not possible.

I created an introduction to MailExtensions here:
https://developer.thunderbird.net/add-ons/mailextensions

background.js and action popups are WebExtension scripts, they only have access to WebExtension APIs but not any of the internal components.

The WindowListener API used by QT is an Experiment API (explained in above link) and allows to execute all the "legacy add-on" code (accessing TBs internal functions and components) as before. The options dialog is still a legacy dialog and invoked by the WL API. The WL API aims to simplify the update process to TB78/MailExtensions. After the initial update, we start to move out legacy things step by step. Tutorials are here:
https://github.com/thundernest/addon-developer-support/issues/37

The third tutorial will be to convert legacy options dialogs from XUL to HTML and call them from WebExtension scripts directly.

**Comment by SamuelPlentz** [comment]
Ok, so later if we convert XUL to pure HTML it will work easier.
For now I could get it to work with the WindowListener.

**Comment by jobisoft** [comment]
merged
