### ISSUE TITLE
Template Formating Lost

### ISSUE THREAD

**Issue by GiddyKippa** [thundernest/quicktext#215]
When I enter the template into the new message it seems to lose the formatting, I've looked around to see if I am formatting the template incorrectly when I create it but can't find a solution to the problem - can you point me in the right direction?

**Comment by SamuelPlentz** [comment]
Can you show the template you want to insert? (remove personal information if needed)
Currently only HTML Syntax can be used to format a template.

For example this template:
`some <b>bold</b> and <i>italic</i> text`

will be converted to this:
some **bold** and _italic_ text

Make sure you choose "Insert as HTML" instead of "Insert as text".

**Comment by SamuelPlentz** [comment]
Did my answer help you?
Can you provide step by step instructions to reproduce the problem otherwise?
