### ISSUE TITLE
Import on startup does not work

### ISSUE THREAD

**Issue by ArseneLup** [thundernest/quicktext#228]
Thunderbird 78.6.1 (issue already with 78.5.1)
Quicktext v 3.5
Windows 10

Hi, first of all, thank you for your great addin!
Unfortunately I have an issue with the import on startup function. I have a shared XML on a network drive which I used to deploy adding the line "user_pref("quicktext.defaultImport", "U:\\Quicktext_mailtemplates.xml");   into the users Thunderbird prefs.js file.
I don't exactly know when this stopped working.

The error console is giving me:
[Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.create]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: chrome://quicktext/content/modules/wzQuicktext.jsm :: loadSettings :: line 163"  data: no] wzQuicktext.jsm:163:26
    loadSettings chrome://quicktext/content/modules/wzQuicktext.jsm:163
    onLoad chrome://quicktext/content/scripts/messenger.js:17
    _loadIntoWindow jar:file://///HOMECL03/HOMEVOL03/CISS/u091yr/_W10SYSTEM/EmailClient/extensions/{8845E3B3-E8FB-40E2-95E9-EC40294818C4}.xpi!/api/WindowListener/implementation.js:573
    onLoadWindow jar:file://///HOMECL03/HOMEVOL03/CISS/u091yr/_W10SYSTEM/EmailClient/extensions/{8845E3B3-E8FB-40E2-95E9-EC40294818C4}.xpi!/api/WindowListener/implementation.js:402
    checkAndRunExtensionCode resource:///modules/ExtensionSupport.jsm:220
    _checkAndRunMatchingExtensions resource:///modules/ExtensionSupport.jsm:195
    _addToListAndNotify resource:///modules/ExtensionSupport.jsm:179
    _waitForLoad resource:///modules/ExtensionSupport.jsm:156

When I try to add the path manually via the GUI, i get:
uncaught exception: Object

I there a way to fix this? Maybe other users are experiencing the same issue

regards

**Comment by jobisoft** [comment]
Quicktext has moved towards local storage for its preferences. Also the preferences you were using have been deprecated for ages. Since the local storage currently cannot be set from outside, I added an override preference:

`extensions.quicktext.defaultImportOverride`

If you set that preference, it will override any value set via the gui on next startup. The value should be a path, like:

`C:\Users\John\Documents\GitHub\quicktext\test.xml`

Unreleased, so you need to build from sources to test.
