### ISSUE TITLE
INPUT (text) as option inside INPUT (select)? How to establish order when there are numerous INPUTs? 

### ISSUE THREAD

**Issue by Llexika** [thundernest/quicktext#230]
Hi! First of all I want to say it's the first time I'm using GitHub, and hope I'm going about it okay...

So... I'm trying to make a template that includes a greeting text and name, farewell text, and leaving the cursor positioned in between these. I'm also adding a text to to the subject.  

The greeting text is working fine. What I want to do is place a name by this text, and I am using an INPUT variable with options. Since the default options do not always return the name I want to use, there 2 different paths I've tried and can't get it to work (at least not how I want!):

### 1. My first thought was to use an INPUT (text) as an option in an INPUT (select). I was expecting this would invoke the selection, and allow to insert text as an option:

`[[INPUT=How to salute?|select|[[SCRIPT=GoodMorning]];Hi;Hi again;Hey]] [[INPUT=Name to use|select|[[TO=firstname]];[[TO=displayname]];[[TO=nickname]];[[INPUT=Write name]]]],`

The idea is for me to only insert with [[INPUT=Write name]] if the previous options do not return the name I want. What this does is call the [[INPUT=Write name]] first, and then allow it as an option in the selections.

### 2. To try to get around the previous option, I thought about using the INPUT (select) first, and then an INPUT (text). 

`[[INPUT=How to salute?|select|[[SCRIPT=GoodMorning]];Hi;Hi again;Hey]] [[INPUT=Name to use|select|[[TO=firstname]];[[TO=displayname]];[[TO=nickname]]]] [[INPUT=Write name]],`

I assmued that if I cancelled instead of selecting an option on the INPUT (select) because the options did not return the name I wanted, I'd then get the INPUT (text), and could write what I wanted. This would work, but it invokes [[INPUT=Write name]] before the first INPUT (select), and the whole idea is to _only_ use the INPUT (text) if I want to insert something not returned by the INPUT (select).

### Possible solution?

I'm guessing that a solution to this would be to run a script where if INPUT (select) does not return a value (is cancelling on the pop up considered "no value"?), then INPUT (text) would run. I've been doing research and looking at the different scripts around, but unfortunately my knowledge to all this is new and limited, and have no idea on how to write this! :( 

### Full template issues

So the template I've created is as attached, and besides the issue exposed earlier regarding the name, for some reason the different INPUTs are not displaying in the order they appear. The INPUT for the subject pops up first, which is fine, but then the order is:

1. [[INPUT=Write name]]
2. [[INPUT=Good bye phrases|select|Regards;Kind regards;Take care;Stay safe]]
3. [[INPUT=How to salute?|select|[[SCRIPT=GoodMorning]];Hi;Hi again;Hey]]
4. [[INPUT=Name to use|select|[[TO=firstname]];[[TO=displayname]];[[ORGHEADER=to]];[[TO=nickname]]]]

How can I establish the order? Is that at all possible? 

![3-2-2021 19 2 8 1](https://user-images.githubusercontent.com/78497820/106791924-d8c56300-6655-11eb-91c8-9b0cdc62fbc8.jpg)

I hope I've explained myself correctly - and that my current procedures and desired "returns" are understood.

Thanks!

**Comment by SamuelPlentz** [comment]
Hi you did explain your problem well.

Things you could / should do to prevent the problems:

1. You stated:

> Since the default options do not always return the name I want to use

IMO that's the main problem. You should consider to keep your address book well organized. Each time I see one of my templates failing to determine the correct firstname, surname or nickname, I open the address book and add or correct the incomplete contact fields.

That way there should be no need to use `[[INPUT=Write name|text]]`. Also you add the name once. Otherwise you need to write the name of that person each time you send an email to him.

2. You should consider to create several small presets instead of a big one.

Template "Formal":
```
[[INPUT=How to salute?|select|[[SCRIPT=GoodMorning]];Hi;Hi again;Hey]] [[TO=lastname]],

[[CURSOR]]

[[INPUT=Good bye phrases|select|Regards;Kind regards;Take care;Stay safe]]
```

Template "Informal":
```
[[INPUT=How to salute?|select|[[SCRIPT=GoodMorning]];Hi;Hi again;Hey]] [[TO=firstname]],

[[CURSOR]]

[[INPUT=Good bye phrases|select|Regards;Kind regards;Take care;Stay safe]]
```

Template "Friends":
```
[[INPUT=How to salute?|select|[[SCRIPT=GoodMorning]];Hi;Hi again;Hey]] [[TO=nickname]],

[[CURSOR]]

[[INPUT=Good bye phrases|select|Regards;Kind regards;Take care;Stay safe]]
```

IMO it is very convenient to select the proper template in the Quicktext toolbar, instead of answering `INPUT`-questions.

3. Perhaps you should have a look at the community script [ToNickname](https://github.com/jobisoft/quicktext/wiki/Script:-ToNickname) do combine `[[TO=firstname]]` and `[[TO=nickname]]` by `[[SCRIPT=ToNickname]]`

4. Answer to the original questions:

> The idea is for me to only insert with [[INPUT=Write name]] if the previous options do not return the name I want.
> How can I establish the order? Is that at all possible?

That is currently unsupported to delay the validation of unused `INPUT` selections. AFAIR the template is parsed backwards, because of nested tags need to be evaluated first. That's also the reason for the unexpected order of the `INPUT`-tags.

Personally I use lots of small templates:
```
Group: one person
    > Template: Hello [[SCRIPT=ToNickname]],
    > Template: Dear [[SCRIPT=ToNickname]],
Group: one person formal
    > Template: Dear Mr. [[TO=lastname]],
    > Template: Dear Ms. [[TO=lastname]],
Group: several persons
    > Template: Hello together,
    > Template: Dear Ladies and Gentlemen,
```

Its not so easy to port my German templates to english. But the list above should give you an idea.

**Comment by jobisoft** [comment]
Correct. Thanks @SamuelPlentz
