### ISSUE TITLE
lost templates after updating

### ISSUE THREAD

**Issue by ioweb-gr** [thundernest/quicktext#233]
Thunderbird and quicktext got updated today and I lost all my templates. It seems that uninstalling the extension and reinstalling restored them. Any ideas what this bug is?

**Comment by Nudin** [comment]
I had the same issue – but I wouldn't describe it as "all templates got lost" but more like Quicktext wasn't showing up in the interface (also not in the menu). Thanks @ioweb-gr for the tip with reinstalling – worked for me!

**Comment by ioweb-gr** [comment]
@Nudin no problem. It gave me quite a scare at first haha

**Comment by Nudin** [comment]
The problem occurs now after every restart of quicktext.

**Comment by jobisoft** [comment]
Could you export your templates, create a new TB profile, import them again and check if the behavior persists?

**Comment by Nudin** [comment]
I have to reject my previous statement, it didn't disappear when I just tested it (without creating a new profile) – but it disappeared multiple times in the past. Maybe after each thunderbird update? I think there is no easy way to find out until it happens again.

**Comment by burkingman** [comment]
Had a similar problem: templates stopped working with Thunderbird 78.7.1 (Linux version), QuickText button still showed up in the toolbar but didn't do anything. Managed to get it working by simply disabling then re-enabling the extension (rather than reinstalling). Possible bug: using the menu bar from the top of the Thunderbird Window, I can see a QuickText item in the Tools menu, but if I open the "hamburger menu" from the right of the toolbar instead, the Tools menu shows some empty space at the bottom, but no QuickText item. Reinstalling the extension didn't help. (Overall, it's usable for me, but I'm reporting this in case it might be helpful.)

**Comment by jobisoft** [comment]
Quicktext should not appear in the tools menu anymore. We have the dedicated button in the toolbar now and the Quicktext settings window can also be opened from the add-on manager. Either via the new wrench icon or via the options entry in the ... menu. The unreleased developer version (3.7b1) is a bit more stable here, the released version on ATN might have some issues with the options in the add-on manager, but it should always work via the dedicated buttons in the toolbars.

Closing this. If the "my templates are lost on every restart" persists with 3.7b1, please open a new issue.
