### ISSUE TITLE
Move screenshot folder and contents to wiki repository

### ISSUE THREAD

**Issue by chrisschnei** [thundernest/quicktext#276]
Hello,
the images in screenshot folder are not referenced or used by extension code.
Would it therefore make sense moving them to wiki repository?
File URLs would then be coupled to wiki repository instead of specific extension development branches.

**Comment by jobisoft** [comment]
Am I using them in the Wiki? I thought those are the screenshots for ATN. I will check later.
-------- Ursprüngliche Nachricht --------Von: Christian Schneider ***@***.***> Datum: 24.11.21  13:52  (GMT+01:00) An: jobisoft/quicktext ***@***.***> Cc: Subscribed ***@***.***> Betreff: [jobisoft/quicktext] Move screenshot folder and contents to wiki repository (Issue #276) 
Hello,
the images in screenshot folder are not referenced or used by extension code.
Would it therefore make sense moving them to wiki repository?
File URLs would then be coupled to wiki repository instead of specific extension development branches.

**Comment by chrisschnei** [comment]
Hello John,
thanks for your answer. The images are for example referenced in the extension introduction article.
I already created branches which could be intergrated.

**Comment by chrisschnei** [comment]
Checked the links on ATN which refer to https://addons.thunderbird.net/user-media/previews/full/0/*.png.
Seems like extension images displayed on ATN site are uploaded separately through developer.

**Comment by jobisoft** [comment]
Yes, but I want to have a versioned copy of those screenshots, when something happens to ATN. I personally think it is ok to have the screenshots in the repo, so everybody who clones and builds QT also has those screenshots to know what to expect. 

Cloning the wiki only works from the command line and not using GitHub Desktop. I do not want to use the wiki repo beyond its standard features.

**Comment by chrisschnei** [comment]
Ok, always good to have a backup. I will close this ticket.
