### ISSUE TITLE
Cannot save in TB60

### ISSUE THREAD

**Issue by jobisoft** [thundernest/quicktext#29]
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFileOutputStream.init] wzQuicktext.js:623

**Comment by jobisoft** [comment]
On my (windows) system, TB was not able to write to the template file due to a permission problem. I was not able to fix that on the file itself. TB was also not able to delete the file. This happend after updating to TB 60.

There is nothing the AddOn can do to fix this.

Solution: Copy the template file (inside the quicktext folder in your TB profile), delete the original one and rename the copy back to "templates.xml". Worked for me.

**Comment by kicktipp** [comment]
Didn't work for me. Because of this Bug https://github.com/thundernest/quicktext/issues/20 I need to import my file manually. But Quicktext can't save it. So I have to import my templates after each restart of TB. Very annoying. 

Should be labeled "bug" and not "wontfix"

**Comment by kicktipp** [comment]
Ok, I resolved this for me. I imported an XML File which was encoded in ISO-8859-1. But Quicktext uses some strange UTF-16 Format. Strange is, that importing my XML File worked fine. I could see all templates in the Quicktext Plugin. Just "Save" didn't work. But after closing the Quicktext GUI, I could use it as normal. Because of this I thought the save operation was broken, but it was the import operation. This can be closed as it should be fixed with the new file format (UTF-8 instead of UTF-16).
