### ISSUE TITLE
edit the  <head>

### ISSUE THREAD

**Issue by sebschopf** [thundernest/quicktext#292]
Hello,
It is possible to edit the `<head>` in the template ?

### My code
```
<!DOCTYPE html><html>
  
<head>
    <meta http-equiv="content-type" content="text/html; charset=">
    <meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=5.0, minimum-scale=0.86">
    <meta name="x-apple-disable-message-reformatting">
</head>
<body>
...
```
### The original code when "new message" or alternativ (forward, answere...) is selected
```
<!DOCTYPE html><html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=">
  </head>
  <body>
    <p><br>
    </p>
  </body>
</html>
```

### Fataly the code is broken if i putt my template :

```
<!DOCTYPE html><html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=">
  </head>
  <body>
    <p> </p>
    <p>
      <meta http-equiv="content-type" content="text/html; charset=">
      <meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=5.0, minimum-scale=0.86">
      <meta name="x-apple-disable-message-reformatting">
      <div>
...
```
There is a subtil tips for that ?
Thx for your attention and best regards

**Comment by SamuelPlentz** [comment]
I also tried and failed. Don't know if this is technically possible, as we only insert to the body.

**Comment by jobisoft** [comment]
I close this as we do not support this.

**Comment by tamas646** [comment]
Hi!
Would it be possible to add a new insert type to the templates (besides `Plain text` and `HTML`)?
The new insert type could be `Full HTML` (or something similar), and it could be used to completely replace the HTML content with the template value.
This could resolve the `<head>` issue as well. We just need to find a way to replace the entire email content, and I think it's possible because there are some HTML editor addons out there which do the same.

**Comment by tamas646** [comment]
@sebschopf, @SamuelPlentz  I managed to solve the `<head>` problem.

I made a script that replaces the entire html content of the editor:

`SetHTMLContent`:
```js
let html = this.mVariables[0];
this.mWindow.gMsgCompose.editor.rebuildDocumentFromSource(html);
return '';
```

Usage:
```
[[SCRIPT=SetHTMLContent|<!DOCTYPE html><html><head>...</head><body>...</body></html>]]
```
or with `FILE`:
```
[[SCRIPT=SetHTMLContent|[[FILE=~/path/to/file.html]]]]
```

**Note:** if your HTML file contains CSS comments make sure that the last comment starts with 2 asterisks (`/** ... */`) instead of 1 (`/* ... */`).

I don't know why but if the last CSS comment starts with 1 asterisk, Quicktext will mess up the mail body by inserting the html code twice.

**Thunderbird version:** 128.2.3esr
**Quicktext version:** 5.16
