### ISSUE TITLE
Problems using Cardbook Extension

### ISSUE THREAD

**Issue by stefanbollmann** [thundernest/quicktext#51]
If I use Quicktext together with Cardbook addresses and use the Last Name field, Displayname will be inserted:
The Template:   
Sehr geehrter Herr [[TO=lastname]],
inserts:  
Sehr geehrter Herr [[TO=displayname]],

Quicktext Version 1.2
Thunderbird Version 60.4.0 (64 Bit)

**Comment by jobisoft** [comment]
Quicktext has no interface to CardBook at all.

**Comment by ovari** [comment]
What is the best way forward to enable Quicktext add-on to support CardBook address books?

https://gitlab.com/CardBook/CardBook/issues/522

Thank you

**Comment by CardBook** [comment]
hi John

do you need help ?

**Comment by jobisoft** [comment]
I am basically moderating this repository and if i find time, I try to fix bugs. However, I do not have the time to implement feature requests. If you have time, go ahead. :-)

**Comment by stefanbollmann** [comment]
This is no feature, it's bug in quicktext or in cardbook.

**Comment by jobisoft** [comment]
Circling back to this, I do not believe I can do something here.

Quicktext is only accessing the standard address book (as it does not know cardbook). If you have the feeling, that it returns a wrong value, because it is not the one you have in your cardbook address book(s), please check your standard address book(s) - which are still there as well probably - because that is where Quicktext is looking. Maybe you updated that contact in cardbook after you made the initial move from the standard address book to the cardbook address book.

You may want to check out TbSync and its CalDAV & CardDAV provider as a well suited alternative to cardbook, which is using the (heavily updated) standard address book.
https://addons.thunderbird.net/addon/tbsync/
https://addons.thunderbird.net/addon/dav-4-tbsync/

**Comment by ovari** [comment]
> You may want to check out TbSync and its CalDAV & CardDAV provider as a well suited alternative to cardbook, which is using the (heavily updated) standard address book.

If TbSync is a well suited alternative to CardBook, why would [simon](https://gitlab.com/sicro) write:
> I just switched from TBsync to CardBook!
> https://gitlab.com/CardBook/CardBook/issues/755#note_260516943

Will the

>  (heavily updated) standard address book

 have all the features of CardBook by Thunderbird 76?

The [Thunderbird Beta Notes](https://www.thunderbird.net/thunderbird/72.0beta/releasenotes/) (beta versions from 69 to 72) don't seem to mention any updates to the address book. Can the address book updates please be added to the release notes?

What do you think?

Thank you

**Comment by jobisoft** [comment]
> why would simon write:

I cannot read his mind, so I cannot answer that. Maybe ask him?

> have all the features of CardBook by Thunderbird 76?

Have you tried TbSync with TB68? What is missing?

> The Thunderbird Beta Notes (beta versions from 69 to 72) don't seem to mention any updates to the address book.

I have not seen any Add-On, whose features where published in the TB release notes. Why should they start doing that for TbSync?
